server.port=8080

spring.application.name=ecommerce-realtime-service

logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG

#config sql postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_vibe
spring.datasource.username=sa
spring.datasource.password=sapassword
